name: Go

on:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:

  go:
    uses: estenrye/.github/.github/workflows/golang-build-and-test.yml@v0.1.5

  docker:
    uses: estenrye/.github/.github/workflows/docker-multiarch-build-and-push.yml@v0.1.5
    with:
      push: false
      image_name: ${{ github.event.repository.name }}
    secrets:
      registry_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}