---
name: docker
on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: 'ubuntu-latest'
      docker_context:
        type: string
        default: '.'

jobs:
  buildx:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          context: ${{ inputs.docker_context }}
      
      