---
name: golang
on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: 'ubuntu-latest'
      golang_version:
        type: string
        default: '1.20.x'

jobs:
  build-and-test:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.golang_version }}
     
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test with Go
        run: go test -json > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json  
  